---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "CPE Course Review"
  description: "API เฉพาะสำหรับการรีวิววิชาภายในภาควิชาวิศวกรรมคอมพิวเตอร์"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/v1"
tags:
- name: "วิชา"
  description: "เข้าถึงข้อมูลวิชาต่างๆ"
- name: "รีวิว"
  description: "เข้าถึงข้อมูลรีวิวต่างๆ ของวิชาหนึ่งๆ"
schemes:
- "http"
paths:
  /courses:
    get:
      tags:
      - "วิชา"
      summary: "รายการวิชาทั้งหมด"
      description: "แสดงรายการวิชาทั้งหมดที่มีในระบบ"
      operationId: "getCourse"
      produces:
      - "application/json"
      parameters:
        - name: "query"
          in: "query"
          description: "คำค้นหารายวิชา"
          type: "string"
      responses:
        200:
          description: "ปกติ"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CourseOverview"
  /course/{courseId}:
    get:
      tags:
      - "วิชา"
      summary: "รายละเอียดวิชา"
      description: "แสดงข้อมูลรายละเอียดของวิชาที่ระบุ"
      operationId: "getCourseById"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "รหัสวิชาของมหาวิทยาลัย"
        required: true
        type: "string"
      responses:
        200:
          description: "ปกติ"
          schema:
            $ref: "#/definitions/CourseDetail"
        404:
          description: "ไม่พบวิชา"
  /course/{courseId}/reviews:
    get:
      tags:
      - "รีวิว"
      summary: "รายการรีวิวเบื้องต้น"
      description: "แสดงรายการข้อมูลการรีวิวเบื้องต้นของวิชาที่ระบุ"
      operationId: "getReviewOverviewByCourseId"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "รหัสวิชาของมหาวิทยาลัย"
        required: true
        type: "string"
      - name: "limit"
        in: "query"
        description: "จำนวนรีวิวที่แสดงสูงสุด"
        type: "number"
        default: 10,
        minimum: 1
        maximum: 1000
      - name: "offset"
        in: "query"
        description: "จำนวนรีวิวที่ข้ามไปแล้ว"
        type: "number"
        default: 0
        minimum: 0
      responses:
        200:
          description: "ปกติ"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ReviewOverview"
        404:
          description: "ไม่พบวิชา"
    post:
      tags:
        - "รีวิว"
      summary: "เพิ่มรีวิว"
      description: "เพิ่มรีวิวเข้าไปยังวิชาที่ระบุ"
      operationId: "addReview"
      produces:
        - "application/json"
      parameters:
        - name: "courseId"
          in: "path"
          description: "รหัสวิชาของมหาวิทยาลัย"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "ข้อมูลรีวิว"
          required: true
          schema:
            $ref: "#/definitions/ReviewDetail"
      responses:
        201:
          description: "สร้างรีวิวสำเร็จ"
        404:
          description: "ไม่พบวิชา"
  /course/{courseId}/reviews/detail:
    get:
      tags:
      - "รีวิว"
      summary: "รายการรีวิวโดยละเอียด"
      description: "แสดงรายการข้อมูลการรีวิวทั้งหมดของวิชาที่ระบุ"
      operationId: "getReviewDetailByCourseId"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "รหัสวิชาของมหาวิทยาลัย"
        required: true
        type: "string"
      - name: "limit"
        in: "query"
        description: "จำนวนรีวิวที่แสดงสูงสุด"
        type: "number"
        default: 10,
        minimum: 1
        maximum: 20
      - name: "offset"
        in: "query"
        description: "จำนวนรีวิวที่ข้ามไปแล้ว"
        type: "number"
        default: 0
        minimum: 0
      responses:
        200:
          description: "ปกติ"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ReviewDetail"
        404:
          description: "ไม่พบวิชา"
definitions:
  CourseOverview:
    type: "object"
    properties:
      course_id:
        type: "string"
        description: "รหัสวิชาของมหาวิทยาลัย"
      course_name_th:
        type: "string"
        description: "ชื่อวิชา (ภาษาไทย)"
      course_name_en:
        type: "string"
        description: "ชื่อวิชา (ภาษาอังกฤษ)"
      course_type:
        type: "string"
        description: "ประเภทวิชา"
        enum:
        - "me"
        - "fe"
        - "ge"
    example:
      course_id: "261200"
      course_name_th: "การเขียนโปรแกรมเชิงวัตถุ"
      course_name_en: "Object-Oriented Programming"
      course_type: "me"
  CourseDetail:
    type: "object"
    allOf:
      - $ref: "#/definitions/CourseOverview"
    properties:
      course_description:
        type: "string"
        description: "คำอธิบายของวิชา"
      course_lecturers:
        type: "array"
        description: "ชื่ออาจารย์ผู้สอน"
        items:
          type: "string"
      course_location:
        type: "string"
        description: "สถานที่เรียน"
      course_schedule:
        type: "array"
        description: "เวลาเรียน"
        items:
          $ref: "#/definitions/CourseTime"
      course_rooms:
        type: "array"
        description: "ห้องเรียน"
        items:
          type: "string"
    example:
        course_id: "261361"
        course_name_th: "การเขียนโปรแกรมเชิงวัตถุ"
        course_name_en: "Object-Oriented Programming"
        course_type: "me"
        course_description: "เรียนเกี่ยวกับการเขียนโปรแกรมเชิงวัตถุ"
        course_lecturer: ["พี่ชิณสุดหล่อ"]
        course_location: "อาคาร 3"
        course_schedule:
          - start_hour: 8
            start_minute: 0
            end_hour: 11
            end_minute: 0
            days: ["mon", "thu"]
          - start_hour: 8
            start_minute: 0
            end_hour: 11
            end_minute: 0
            days: ["tue", "fri"]
        course_room: ["301", "302"]
  CourseTime:
    type: "object"
    properties:
      start_hour:
        type: "integer"
        format: "int64"
        minimum: 0
        maximum: 23
      start_minute:
        type: "integer"
        format: "int64"
        minimum: 0
        maximum: 59
      end_hour:
        type: "integer"
        format: "int64"
        minimum: 0
        maximum: 23
      end_minute:
        type: "integer"
        format: "int64"
        minimum: 0
        maximum: 59
      days:
        type: "array"
        items:
          type: "string"
          enum:
          - "mon"
          - "tue"
          - "wed"
          - "thu"
          - "fri"
          - "sat"
          - "sun"
    example:
      start_hour: 8
      start_minute: 0
      end_hour: 11
      end_minute: 0
      days: ["mon", "thu"]
  ReviewOverview:
    type: "object"
    properties:
      rating:
        type: "integer"
        format: "int64"
        minimum: 1
        maximum: 5
      grade:
        type: "string"
        enum:
          - "a"
          - "b+"
          - "b"
          - "c+"
          - "c"
          - "d+"
          - "d"
          - "f"
          - "-"
    example:
      rating: 5
      grade: "a"
  ReviewDetail:
    type: "object"
    allOf:
      - $ref: "#/definitions/ReviewOverview"
    properties:
      id:
        type: "integer"
        format: "int64"
      content:
        type: "string"
      classroom_environment:
        type: "string"
      examination_format:
        type: "string"
      exercise_format:
        type: "string"
      grading_method:
        type: "array"
        items:
          type: "string"
          enum:
            - "midterm"
            - "final"
      semester:
        type: "string"
        enum:
          - "1"
          - "2"
          - "3"
      year:
        type: "integer"
        format: "พุทธศักราช"
    example:
        id: 1
        rating: 5
        grade: "a"
        content: "เรียนเข้าใจง่ายมาก แต่ TA ตรวจค่อนข้างเข้มข้นและช้ามาก"
        classroom_environment: "เรียนในห้องแอร์เย็นสบาย"
        examination_format: "สอบปลายภาค"
        exercise_format: "เขียนโปรแกรม"
        grading_method: ["midterm", "final"]
        semester: "2"
        year: 2564